create table person (
    id integer generated by default as identity primary key,
    first_name varchar(100) not null,
    last_name varchar(100) not null,
    date_of_birth date not null,
    email varchar(100) unique not null,
    password varchar not null,
    role varchar(100) not null,
    registered_at timestamp not null
);

create table book (
    id integer generated by default as identity primary key,
    title varchar(100) not null,
    author varchar(100) not null,
    description text not null,
    copies integer not null,
    copies_available integer not null,
    img text not null
);

create table genre (
    id integer generated by default as identity primary key,
    description varchar(50) unique not null
);

create table book_genre (
    book_id integer not null references book (id) on delete cascade,
    genre_id integer not null references genre (id) on delete cascade,
    primary key(book_id, genre_id)
);

create table checkout (
    id integer generated by default as identity primary key,
    person_email varchar(100) not null references person (email) on delete cascade,
    book_id integer not null references book (id) on delete cascade,
    checkout_date date not null,
    return_date date not null
);

create table review (
    id integer generated by default as identity primary key,
    person_email varchar(100) not null,
    person_first_name varchar(100) not null,
    person_last_name varchar(100) not null,
    book_id integer not null references book (id) on delete cascade,
    date timestamp not null,
    rating decimal(3, 2) not null,
    review_description text
);

create table history_record (
    id integer generated by default as identity primary key,
    person_email varchar(100) not null references person (email) on delete cascade,
    book_id integer not null references book (id) on delete cascade,
    checkout_date date not null,
    return_date date not null
);

create table discussion (
    id integer generated by default as identity primary key,
    person_email varchar(100) not null references person (email) on delete cascade,
    title varchar(100) not null,
    question text not null,
    admin_email varchar(100),
    response text,
    closed boolean default false not null
);

create table payment (
    id integer generated by default as identity primary key,
    person_email varchar(100) unique not null references person (email) on delete cascade,
    amount decimal(10, 2) not null
);

insert into genre (id, description) values (1, 'Science Fiction');
insert into genre (id, description) values (2, 'Fantasy');
insert into genre (id, description) values (3, 'Adventure');
insert into genre (id, description) values (4, 'Novel');
insert into genre (id, description) values (5, 'Dystopia');
insert into genre (id, description) values (6, 'Detective');
insert into genre (id, description) values (7, 'Short Stories');
insert into genre (id, description) values (8, 'Romance');
insert into genre (id, description) values (9, 'LitRPG');